---
title: "Running fastMNN on Seurat Objects"
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
output: 
  github_document:
    html_preview: true
    toc: true
    toc_depth: 3
  html_document:
    df_print: kable
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 95),
  message = FALSE,
  warning = FALSE
)
```

```{r packages}
library(Seurat)
library(SeuratData)
library(SeuratWrappers)
```

## {.tabset .tabset-pills}

### PBMC

```{r broad, cache=TRUE}
data("broad")
broad <- NormalizeData(broad)
broad <- FindVariableFeatures(broad)
broad <- ScaleData(broad, split.by = 'Method')
broad <- RunFastMNN(object.list = SplitObject(broad, split.by = 'Method'))
broad <- RunUMAP(broad, reduction = 'mnn', dims = 1:30)
DimPlot(broad, group.by = 'Method', label = TRUE) + NoLegend()
```

### Immune/Stim

```{r immune_stim, cache=TRUE}
data("immune")
immune <- NormalizeData(immune)
immune <- FindVariableFeatures(immune)
immune <- ScaleData(immune, split.by = 'stim')
immune <- RunFastMNN(object.list = SplitObject(immune, split.by = 'stim'))
immune <- RunUMAP(immune, reduction = 'mnn', dims = 1:30)
DimPlot(immune, group.by = 'stim', label = TRUE) + NoLegend()
```

### Pancreas

```{r pancreas, cache=TRUE}
data("panc8")
panc8 <- NormalizeData(panc8)
panc8 <- FindVariableFeatures(panc8)
panc8 <- ScaleData(panc8, split.by = 'replicate')
panc8 <- RunFastMNN(object.list = SplitObject(panc8, split.by = 'replicate'))
panc8 <- RunUMAP(panc8, reduction = 'mnn', dims = 1:30)
DimPlot(panc8, group.by = 'replicate', label = TRUE) + NoLegend()
```
