// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// banksy_forward_cpp
NumericMatrix banksy_forward_cpp(List gcm_i_list, List gcm_p_list, List gcm_x_list, int gcm_nrow, int n_cells, List W_i_list, List W_p_list, List W_x_list, IntegerVector W_ncol_vec, List group_idx_list, NumericMatrix x, bool split_scale, NumericMatrix mu_own_mat, NumericMatrix sd_own_mat, NumericMatrix mu_h0_mat, NumericMatrix sd_h0_mat, NumericVector lam, Nullable<LogicalVector> valid_own_, Nullable<LogicalVector> valid_h0_);
RcppExport SEXP _SeuratWrappers_banksy_forward_cpp(SEXP gcm_i_listSEXP, SEXP gcm_p_listSEXP, SEXP gcm_x_listSEXP, SEXP gcm_nrowSEXP, SEXP n_cellsSEXP, SEXP W_i_listSEXP, SEXP W_p_listSEXP, SEXP W_x_listSEXP, SEXP W_ncol_vecSEXP, SEXP group_idx_listSEXP, SEXP xSEXP, SEXP split_scaleSEXP, SEXP mu_own_matSEXP, SEXP sd_own_matSEXP, SEXP mu_h0_matSEXP, SEXP sd_h0_matSEXP, SEXP lamSEXP, SEXP valid_own_SEXP, SEXP valid_h0_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type gcm_i_list(gcm_i_listSEXP);
    Rcpp::traits::input_parameter< List >::type gcm_p_list(gcm_p_listSEXP);
    Rcpp::traits::input_parameter< List >::type gcm_x_list(gcm_x_listSEXP);
    Rcpp::traits::input_parameter< int >::type gcm_nrow(gcm_nrowSEXP);
    Rcpp::traits::input_parameter< int >::type n_cells(n_cellsSEXP);
    Rcpp::traits::input_parameter< List >::type W_i_list(W_i_listSEXP);
    Rcpp::traits::input_parameter< List >::type W_p_list(W_p_listSEXP);
    Rcpp::traits::input_parameter< List >::type W_x_list(W_x_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type W_ncol_vec(W_ncol_vecSEXP);
    Rcpp::traits::input_parameter< List >::type group_idx_list(group_idx_listSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type split_scale(split_scaleSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mu_own_mat(mu_own_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sd_own_mat(sd_own_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mu_h0_mat(mu_h0_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sd_h0_mat(sd_h0_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< Nullable<LogicalVector> >::type valid_own_(valid_own_SEXP);
    Rcpp::traits::input_parameter< Nullable<LogicalVector> >::type valid_h0_(valid_h0_SEXP);
    rcpp_result_gen = Rcpp::wrap(banksy_forward_cpp(gcm_i_list, gcm_p_list, gcm_x_list, gcm_nrow, n_cells, W_i_list, W_p_list, W_x_list, W_ncol_vec, group_idx_list, x, split_scale, mu_own_mat, sd_own_mat, mu_h0_mat, sd_h0_mat, lam, valid_own_, valid_h0_));
    return rcpp_result_gen;
END_RCPP
}
// banksy_adjoint_cpp
NumericMatrix banksy_adjoint_cpp(List gcm_i_list, List gcm_p_list, List gcm_x_list, int gcm_nrow, int n_cells, List W_i_list, List W_p_list, List W_x_list, IntegerVector W_ncol_vec, List group_idx_list, NumericMatrix xo_s, NumericMatrix xh_s, NumericVector adj_o, NumericVector adj_h, bool split_scale, NumericMatrix mu_own_mat, NumericMatrix sd_own_mat, NumericMatrix mu_h0_mat, NumericMatrix sd_h0_mat, NumericVector lam);
RcppExport SEXP _SeuratWrappers_banksy_adjoint_cpp(SEXP gcm_i_listSEXP, SEXP gcm_p_listSEXP, SEXP gcm_x_listSEXP, SEXP gcm_nrowSEXP, SEXP n_cellsSEXP, SEXP W_i_listSEXP, SEXP W_p_listSEXP, SEXP W_x_listSEXP, SEXP W_ncol_vecSEXP, SEXP group_idx_listSEXP, SEXP xo_sSEXP, SEXP xh_sSEXP, SEXP adj_oSEXP, SEXP adj_hSEXP, SEXP split_scaleSEXP, SEXP mu_own_matSEXP, SEXP sd_own_matSEXP, SEXP mu_h0_matSEXP, SEXP sd_h0_matSEXP, SEXP lamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type gcm_i_list(gcm_i_listSEXP);
    Rcpp::traits::input_parameter< List >::type gcm_p_list(gcm_p_listSEXP);
    Rcpp::traits::input_parameter< List >::type gcm_x_list(gcm_x_listSEXP);
    Rcpp::traits::input_parameter< int >::type gcm_nrow(gcm_nrowSEXP);
    Rcpp::traits::input_parameter< int >::type n_cells(n_cellsSEXP);
    Rcpp::traits::input_parameter< List >::type W_i_list(W_i_listSEXP);
    Rcpp::traits::input_parameter< List >::type W_p_list(W_p_listSEXP);
    Rcpp::traits::input_parameter< List >::type W_x_list(W_x_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type W_ncol_vec(W_ncol_vecSEXP);
    Rcpp::traits::input_parameter< List >::type group_idx_list(group_idx_listSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xo_s(xo_sSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xh_s(xh_sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type adj_o(adj_oSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type adj_h(adj_hSEXP);
    Rcpp::traits::input_parameter< bool >::type split_scale(split_scaleSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mu_own_mat(mu_own_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sd_own_mat(sd_own_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mu_h0_mat(mu_h0_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sd_h0_mat(sd_h0_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lam(lamSEXP);
    rcpp_result_gen = Rcpp::wrap(banksy_adjoint_cpp(gcm_i_list, gcm_p_list, gcm_x_list, gcm_nrow, n_cells, W_i_list, W_p_list, W_x_list, W_ncol_vec, group_idx_list, xo_s, xh_s, adj_o, adj_h, split_scale, mu_own_mat, sd_own_mat, mu_h0_mat, sd_h0_mat, lam));
    return rcpp_result_gen;
END_RCPP
}
// h0_group_stats_cpp
List h0_group_stats_cpp(List gcm_i_list, List gcm_p_list, List gcm_x_list, int gcm_nrow, List W_i_list, List W_p_list, List W_x_list, List group_idx_list);
RcppExport SEXP _SeuratWrappers_h0_group_stats_cpp(SEXP gcm_i_listSEXP, SEXP gcm_p_listSEXP, SEXP gcm_x_listSEXP, SEXP gcm_nrowSEXP, SEXP W_i_listSEXP, SEXP W_p_listSEXP, SEXP W_x_listSEXP, SEXP group_idx_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type gcm_i_list(gcm_i_listSEXP);
    Rcpp::traits::input_parameter< List >::type gcm_p_list(gcm_p_listSEXP);
    Rcpp::traits::input_parameter< List >::type gcm_x_list(gcm_x_listSEXP);
    Rcpp::traits::input_parameter< int >::type gcm_nrow(gcm_nrowSEXP);
    Rcpp::traits::input_parameter< List >::type W_i_list(W_i_listSEXP);
    Rcpp::traits::input_parameter< List >::type W_p_list(W_p_listSEXP);
    Rcpp::traits::input_parameter< List >::type W_x_list(W_x_listSEXP);
    Rcpp::traits::input_parameter< List >::type group_idx_list(group_idx_listSEXP);
    rcpp_result_gen = Rcpp::wrap(h0_group_stats_cpp(gcm_i_list, gcm_p_list, gcm_x_list, gcm_nrow, W_i_list, W_p_list, W_x_list, group_idx_list));
    return rcpp_result_gen;
END_RCPP
}
// h0_group_excess_cpp
List h0_group_excess_cpp(List gcm_i_list, List gcm_p_list, List gcm_x_list, int gcm_nrow, List W_i_list, List W_p_list, List W_x_list, List group_idx_list, IntegerVector clip_genes_r, bool split_scale, NumericMatrix mu_mat, NumericMatrix sd_mat, double scale_max);
RcppExport SEXP _SeuratWrappers_h0_group_excess_cpp(SEXP gcm_i_listSEXP, SEXP gcm_p_listSEXP, SEXP gcm_x_listSEXP, SEXP gcm_nrowSEXP, SEXP W_i_listSEXP, SEXP W_p_listSEXP, SEXP W_x_listSEXP, SEXP group_idx_listSEXP, SEXP clip_genes_rSEXP, SEXP split_scaleSEXP, SEXP mu_matSEXP, SEXP sd_matSEXP, SEXP scale_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type gcm_i_list(gcm_i_listSEXP);
    Rcpp::traits::input_parameter< List >::type gcm_p_list(gcm_p_listSEXP);
    Rcpp::traits::input_parameter< List >::type gcm_x_list(gcm_x_listSEXP);
    Rcpp::traits::input_parameter< int >::type gcm_nrow(gcm_nrowSEXP);
    Rcpp::traits::input_parameter< List >::type W_i_list(W_i_listSEXP);
    Rcpp::traits::input_parameter< List >::type W_p_list(W_p_listSEXP);
    Rcpp::traits::input_parameter< List >::type W_x_list(W_x_listSEXP);
    Rcpp::traits::input_parameter< List >::type group_idx_list(group_idx_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type clip_genes_r(clip_genes_rSEXP);
    Rcpp::traits::input_parameter< bool >::type split_scale(split_scaleSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mu_mat(mu_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sd_mat(sd_matSEXP);
    Rcpp::traits::input_parameter< double >::type scale_max(scale_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(h0_group_excess_cpp(gcm_i_list, gcm_p_list, gcm_x_list, gcm_nrow, W_i_list, W_p_list, W_x_list, group_idx_list, clip_genes_r, split_scale, mu_mat, sd_mat, scale_max));
    return rcpp_result_gen;
END_RCPP
}
// own_excess_cpp
List own_excess_cpp(List gcm_i_list, List gcm_p_list, List gcm_x_list, List group_idx_list, bool split_scale, NumericMatrix mu_mat, NumericMatrix sd_mat, NumericVector mu_vec, NumericVector sd_vec, Nullable<LogicalVector> valid_, double scale_max, int n_genes, int n_cells);
RcppExport SEXP _SeuratWrappers_own_excess_cpp(SEXP gcm_i_listSEXP, SEXP gcm_p_listSEXP, SEXP gcm_x_listSEXP, SEXP group_idx_listSEXP, SEXP split_scaleSEXP, SEXP mu_matSEXP, SEXP sd_matSEXP, SEXP mu_vecSEXP, SEXP sd_vecSEXP, SEXP valid_SEXP, SEXP scale_maxSEXP, SEXP n_genesSEXP, SEXP n_cellsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type gcm_i_list(gcm_i_listSEXP);
    Rcpp::traits::input_parameter< List >::type gcm_p_list(gcm_p_listSEXP);
    Rcpp::traits::input_parameter< List >::type gcm_x_list(gcm_x_listSEXP);
    Rcpp::traits::input_parameter< List >::type group_idx_list(group_idx_listSEXP);
    Rcpp::traits::input_parameter< bool >::type split_scale(split_scaleSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mu_mat(mu_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sd_mat(sd_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu_vec(mu_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sd_vec(sd_vecSEXP);
    Rcpp::traits::input_parameter< Nullable<LogicalVector> >::type valid_(valid_SEXP);
    Rcpp::traits::input_parameter< double >::type scale_max(scale_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n_genes(n_genesSEXP);
    Rcpp::traits::input_parameter< int >::type n_cells(n_cellsSEXP);
    rcpp_result_gen = Rcpp::wrap(own_excess_cpp(gcm_i_list, gcm_p_list, gcm_x_list, group_idx_list, split_scale, mu_mat, sd_mat, mu_vec, sd_vec, valid_, scale_max, n_genes, n_cells));
    return rcpp_result_gen;
END_RCPP
}
// lanczos_set_col
void lanczos_set_col(NumericVector Q, int j, NumericVector v, int n);
RcppExport SEXP _SeuratWrappers_lanczos_set_col(SEXP QSEXP, SEXP jSEXP, SEXP vSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    lanczos_set_col(Q, j, v, n);
    return R_NilValue;
END_RCPP
}
// lanczos_get_col
NumericVector lanczos_get_col(NumericVector Q, int j, int n);
RcppExport SEXP _SeuratWrappers_lanczos_get_col(SEXP QSEXP, SEXP jSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(lanczos_get_col(Q, j, n));
    return rcpp_result_gen;
END_RCPP
}
// lanczos_reorth
NumericVector lanczos_reorth(NumericVector Q, int ncols, NumericVector v, int n);
RcppExport SEXP _SeuratWrappers_lanczos_reorth(SEXP QSEXP, SEXP ncolsSEXP, SEXP vSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type ncols(ncolsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(lanczos_reorth(Q, ncols, v, n));
    return rcpp_result_gen;
END_RCPP
}
// lanczos_norm
double lanczos_norm(NumericVector v);
RcppExport SEXP _SeuratWrappers_lanczos_norm(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(lanczos_norm(v));
    return rcpp_result_gen;
END_RCPP
}
// lanczos_extract
NumericMatrix lanczos_extract(NumericVector Q, NumericMatrix vectors, int n, int work, int npcs);
RcppExport SEXP _SeuratWrappers_lanczos_extract(SEXP QSEXP, SEXP vectorsSEXP, SEXP nSEXP, SEXP workSEXP, SEXP npcsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Q(QSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vectors(vectorsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type work(workSEXP);
    Rcpp::traits::input_parameter< int >::type npcs(npcsSEXP);
    rcpp_result_gen = Rcpp::wrap(lanczos_extract(Q, vectors, n, work, npcs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SeuratWrappers_banksy_forward_cpp", (DL_FUNC) &_SeuratWrappers_banksy_forward_cpp, 19},
    {"_SeuratWrappers_banksy_adjoint_cpp", (DL_FUNC) &_SeuratWrappers_banksy_adjoint_cpp, 20},
    {"_SeuratWrappers_h0_group_stats_cpp", (DL_FUNC) &_SeuratWrappers_h0_group_stats_cpp, 8},
    {"_SeuratWrappers_h0_group_excess_cpp", (DL_FUNC) &_SeuratWrappers_h0_group_excess_cpp, 13},
    {"_SeuratWrappers_own_excess_cpp", (DL_FUNC) &_SeuratWrappers_own_excess_cpp, 13},
    {"_SeuratWrappers_lanczos_set_col", (DL_FUNC) &_SeuratWrappers_lanczos_set_col, 4},
    {"_SeuratWrappers_lanczos_get_col", (DL_FUNC) &_SeuratWrappers_lanczos_get_col, 3},
    {"_SeuratWrappers_lanczos_reorth", (DL_FUNC) &_SeuratWrappers_lanczos_reorth, 4},
    {"_SeuratWrappers_lanczos_norm", (DL_FUNC) &_SeuratWrappers_lanczos_norm, 1},
    {"_SeuratWrappers_lanczos_extract", (DL_FUNC) &_SeuratWrappers_lanczos_extract, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_SeuratWrappers(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
