# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

banksy_forward_cpp <- function(gcm_i_list, gcm_p_list, gcm_x_list, gcm_nrow, n_cells, W_i_list, W_p_list, W_x_list, W_ncol_vec, group_idx_list, x, split_scale, mu_own_mat, sd_own_mat, mu_h0_mat, sd_h0_mat, lam, valid_own_, valid_h0_) {
    .Call(`_SeuratWrappers_banksy_forward_cpp`, gcm_i_list, gcm_p_list, gcm_x_list, gcm_nrow, n_cells, W_i_list, W_p_list, W_x_list, W_ncol_vec, group_idx_list, x, split_scale, mu_own_mat, sd_own_mat, mu_h0_mat, sd_h0_mat, lam, valid_own_, valid_h0_)
}

banksy_adjoint_cpp <- function(gcm_i_list, gcm_p_list, gcm_x_list, gcm_nrow, n_cells, W_i_list, W_p_list, W_x_list, W_ncol_vec, group_idx_list, xo_s, xh_s, adj_o, adj_h, split_scale, mu_own_mat, sd_own_mat, mu_h0_mat, sd_h0_mat, lam) {
    .Call(`_SeuratWrappers_banksy_adjoint_cpp`, gcm_i_list, gcm_p_list, gcm_x_list, gcm_nrow, n_cells, W_i_list, W_p_list, W_x_list, W_ncol_vec, group_idx_list, xo_s, xh_s, adj_o, adj_h, split_scale, mu_own_mat, sd_own_mat, mu_h0_mat, sd_h0_mat, lam)
}

h0_group_stats_cpp <- function(gcm_i_list, gcm_p_list, gcm_x_list, gcm_nrow, W_i_list, W_p_list, W_x_list, group_idx_list) {
    .Call(`_SeuratWrappers_h0_group_stats_cpp`, gcm_i_list, gcm_p_list, gcm_x_list, gcm_nrow, W_i_list, W_p_list, W_x_list, group_idx_list)
}

h0_group_excess_cpp <- function(gcm_i_list, gcm_p_list, gcm_x_list, gcm_nrow, W_i_list, W_p_list, W_x_list, group_idx_list, clip_genes_r, split_scale, mu_mat, sd_mat, scale_max) {
    .Call(`_SeuratWrappers_h0_group_excess_cpp`, gcm_i_list, gcm_p_list, gcm_x_list, gcm_nrow, W_i_list, W_p_list, W_x_list, group_idx_list, clip_genes_r, split_scale, mu_mat, sd_mat, scale_max)
}

own_excess_cpp <- function(gcm_i_list, gcm_p_list, gcm_x_list, group_idx_list, split_scale, mu_mat, sd_mat, mu_vec, sd_vec, valid_, scale_max, n_genes, n_cells) {
    .Call(`_SeuratWrappers_own_excess_cpp`, gcm_i_list, gcm_p_list, gcm_x_list, group_idx_list, split_scale, mu_mat, sd_mat, mu_vec, sd_vec, valid_, scale_max, n_genes, n_cells)
}

lanczos_set_col <- function(Q, j, v, n) {
    invisible(.Call(`_SeuratWrappers_lanczos_set_col`, Q, j, v, n))
}

lanczos_get_col <- function(Q, j, n) {
    .Call(`_SeuratWrappers_lanczos_get_col`, Q, j, n)
}

lanczos_reorth <- function(Q, ncols, v, n) {
    .Call(`_SeuratWrappers_lanczos_reorth`, Q, ncols, v, n)
}

lanczos_norm <- function(v) {
    .Call(`_SeuratWrappers_lanczos_norm`, v)
}

lanczos_extract <- function(Q, vectors, n, work, npcs) {
    .Call(`_SeuratWrappers_lanczos_extract`, Q, vectors, n, work, npcs)
}

